config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }

  def self.search(search)
    if search
      where("name LIKE '%#{search}%'")
    else
      Flat.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.search(params[:search])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit class: "btn btn-outline-primary my-3" %>
  <% end %>

  <%= link_to "Back to flats", flats_path, class: "btn btn-outline-secondary m-1" %>
</div>

app/views/flats/edit.html.erb
<h2 class="border p-2 m-3 rounded">Edit a flat</h2>

<%= render 'form' %>

app/views/flats/index.html.erb
<h2 class="border p-2 m-3 rounded">All of our flats: <%= Flat.count %> available</h1>

<ul class="list-inline">
  <% @flats.each do |flat| %>
    <li class="list-inline-item">
      <div class="card mx-auto" style="width: 24rem;">
        <img src="https://source.unsplash.com/random/300x180" class="card-img-top">
        <div class="card-body">
          <div class="card-header">
            <h3 class="card-title"><%= flat.name %></h3>
          </div>

          <ul class="list-group list-group-flush">
            <li class="list-group-item"><p class="card-text"><%= flat.description %></p></li>
            <li class="list-group-item"><p class="card-text"><%= flat.address %></p></li>
            <li class="list-group-item">
              <div class="d-flex flat-specs-row">
                <div class="d-flex flat-occupancy me-3">
                  <i class="fas fa-user-friends"></i>
                  <p><%= flat.number_of_guests %></p>
                </div>
                <div class="d-flex flat-price">
                  <i class="fas fa-dollar-sign"></i>
                  <p><%= flat.price_per_night %></p>
                </div>
              </div>
            </li>
          </ul>



          <div class="buttons d-flex">
            <%= link_to "More Info", flat_path(flat), class: "btn btn-outline-secondary m-1" %>
            <%= link_to "Edit", edit_flat_path(flat), class: "btn btn-outline-secondary m-1" %>
            <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Really really??"}, class: "btn btn-outline-danger m-1" %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/flats/new.html.erb
<h2 class="border p-2 m-3 rounded">Add new flat</h2>

<%= render 'form' %>

app/views/flats/show.html.erb
<h2 class="border p-2 m-3 rounded"><%= @flat.name %></h2>

<div class="card-body">
  <img src="https://source.unsplash.com/random/300x100" class="card-img-top img-fluid">
  <p class="card-text"><%= @flat.description %></p>
  <p class="card-text"><%= @flat.address %></p>
  <div class="d-flex flat-specs-row mx-3">
    <div class="d-flex flat-occupancy mx-3">
      <i class="fas fa-user-friends"></i>
      <p><%= @flat.number_of_guests %></p>
    </div>
    <div class="d-flex flat-price mx-3">
      <i class="fas fa-dollar-sign"></i>
      <p><%= @flat.price_per_night %></p>
    </div>
  </div>
  <div class="buttons d-flex">
    <%= link_to "Back to flats", flats_path, class: "btn btn-outline-secondary m-1" %>
    <%= link_to "Edit this flat", edit_flat_path(@flat), class: "btn btn-outline-secondary m-1" %>
    <%= link_to "Remove this flat", flat_path(@flat), method: :delete, data: { confirm: "Really really??"}, class: "btn btn-outline-danger m-1" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar bg-white p-3 d-flex">
      <h1>Simple Airbnb</h1>
      <%#= form_for @flats do |f| %>
        <%#= f.input :search, "Search" %>
      <%# end %>

      <input type="text" class="form-control w-25" id="search-input" placeholder="Search">
      <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-secondary my-2 my-sm-0 ml-2" %>
    </div>
    <%= yield %>
  </body>
</html>